language: rust
rust:
  - stable
  - beta
  - nightly
os:
  - linux
env:
  - DATABASE_URL=tet.db
    RUST_BACKTRACE=1
install:
  - cargo install diesel_cli --no-default-features --features sqlite
script:
  - cargo build
  - cargo test
